### ISSUE TITLE
Autostart fail

### ISSUE THREAD

**Issue by ghost** [mariok/pinemup#1]
I created /home/myself/.config/autostart/pinemup.desktop in my Debian 8.1.0 with Cinnamon containing:

[Desktop Entry]
Type=Application
Exec=java -jar pinemup.jar
Hidden=false
X-GNOME-Autostart-enabled=true
Name=Pinemup
Comment=Pinemup

But when I try to start a Cinnamon session I get this message:

http://s18.postimg.org/vc936emqh/pinemup.png

When I start it by clicking two times in the jar file it starts normally.

**Comment by mariok** [comment]
The message "Error - TrayIcon not supported by your system. Exiting..." is shown, if the desktop-environment in use does not provide a tray, where icons can be placed.

As Cinnamon does generally support tray-icons, this is probably related to ongoing initialization (i.e. pinemup checks for TrayIcon support before the tray is initialized properly).

As a workaround, try creating a script, which waits for a few seconds before starting pin 'em up:

```
sleep 10 &&
java -jar pinemup.jar
```

Then add this script to your autostart / desktop-entry instead. Please give some feedback, if this works for you.

**Comment by ghost** [comment]
Wasn't necessary. For some motive it just started working properly.

Thank you very much!
